version: '3'
services:
  vue:
    image: node:14
    tty: true
    ports:
      - 8080:8080
    working_dir: /gt/sc-prog-repos/patientfile/vue-client
#    command: bash -c "npm install && npm run serve"
    volumes:
      - /gt/sc-prog-repos/patientfile/vue-client:/gt/sc-prog-repos/patientfile/vue-client # This will allow hot reloading when files are changed on host
  node:
    image: node:14
    tty: true
    environment:
      - NODE_ENV=development      # This is neededed to load the correct override file from /node-server/config/ folder. For more read node-server/config/readme.md
    ports:
      - 8000:8000
    working_dir: /gt/sc-prog-repos/patientfile/node-server
    command: bash -c "npm install && npm run start"
    volumes:
      -  /gt/sc-prog-repos/patientfile/node-server:/gt/sc-prog-repos/patientfile/node-server # This allows file changes on host to be available inside docker container without recreating docker image. 
      # For reasons of this volume mount see the vue: section comments
